bash ./simulation/data_collection/scripts/weather-0/routes_town05_0.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_1.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_2.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_3.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_4.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_5.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_6.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_7.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_8.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_9.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_10.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_11.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_12.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_13.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_14.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_15.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_16.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_17.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_18.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_19.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_20.sh 
