bash ./simulation/data_collection/scripts/weather-0/routes_town03_0.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_1.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_2.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_3.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_4.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_5.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_6.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_7.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_8.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_9.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_10.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_11.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_12.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_13.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_14.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_15.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_16.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_17.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_18.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_19.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_20.sh 
