bash ./simulation/data_collection/scripts/weather-0/routes_town03_21.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_22.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_23.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_24.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_25.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_26.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_27.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_28.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_29.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_30.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_31.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_32.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_33.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_34.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_35.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_36.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_37.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_38.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_39.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_40.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town03_41.sh 
