bash ./simulation/data_collection/scripts/weather-0/routes_town04_0.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_1.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_2.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_3.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_4.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_5.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_6.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_7.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_8.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_9.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_10.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_11.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_12.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_13.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_14.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_15.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_16.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_17.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_18.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_19.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_20.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_21.sh 
