bash ./simulation/data_collection/scripts/weather-0/routes_town04_22.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_23.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_24.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_25.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_26.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_27.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_28.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_29.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_30.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_31.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_32.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_33.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_34.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_35.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_36.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_37.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_38.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_39.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_40.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_41.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_42.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town04_43.sh 
