bash ./simulation/data_collection/scripts/weather-0/routes_town05_21.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_22.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_23.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_24.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_25.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_26.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_27.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_28.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_29.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_30.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_31.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_32.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_33.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_34.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_35.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_36.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_37.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_38.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_39.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_40.sh 
bash ./simulation/data_collection/scripts/weather-0/routes_town05_41.sh 
